id: P67C16414
initial_creation_type: ocr
source_metadata:
  volumes:
    9b007ac5d6754ba297f14acf3a8ffd41:
      base_file: v097.txt
      image_group_id: I1PD95942
      title: ཚད་མ་རྣམ་པར་ངེས་པ།
      total_pages: 1198
      volume_number: 97
vol2fn:
  v097: v097.txt
